### ISSUE TITLE
Getting distances in result set

### ISSUE THREAD

**Issue by ilblog** [mourner/geokdbush#3]
Hi Vladimir

Do you think there is a chance to get distance with a result somehow?

IL

**Comment by mourner** [comment]
Yes — a few options here:

1. Make the API a bit more complicated by returning an array of `{distance, item}` objects rather than items directly.
2. Let the users calculate distances afterwards. For this, we could expose a `geokdbush.distance(lng1, lat1, lng2, lat2)` method for convenience.

I'm on the fence but inclined towards 2 — although it requires redundant calculations (since internally all the distances are already calculated), this shouldn't be a bottleneck in practice, and would allow keeping the API simpler.

**Comment by ilblog** [comment]
Well 2 looks good

**Comment by ilblog** [comment]
Have an idea. The distance are already computed when you return indexes of NN. Just leave them in some array as a property of KNN index. 

Sync are operations are sync you just ask for NN, get results and if someone wants, gets computed distances also

**Comment by mourner** [comment]
Saving a distances array as an index property is easy, but a bit awkward from the API design standpoint. I might end up going with option 1 since it sounds more straightforward.

**Comment by mourner** [comment]
I went with the option 1 first, but it turned out that performance for the "1000 queries" benchmark decreases by ~20%. Maybe because V8 has a harder time creating arrays of more complex objects?

So I ended up simply exposing a `geokdbush.distance(lon1, lat1, lon2, lat2)` function. It should be fast enough for most practical cases.

**Comment by ilblog** [comment]
If I send you pull rqst code and add options to the `around` fun that will do just 

result.push( options.includeDist ? candidate : candidate.item );

would you merge? No harm to simple API done

**Comment by mourner** [comment]
@ilblog this might be a good solution, although I'm not sure whether it has any performance benefit compared to recalculating distances afterwards. Let me make a benchmark to confirm.

**Comment by ilblog** [comment]
WOW

``` 
while (q.length && q.peek().item) {
            var candidate = q.pop();
            if (candidate.dist > maxDistance) return result;
            result.push(candidate); // this is gamechanger
            if (result.length === maxResults) return result;
}
```
With this change the library become completely different tool. I got not only distance but also original item (not only index). I tweaked my local copy and being happy now.

**Comment by skostojohn** [comment]
I am a beginning developer and struggling to use the maxDistance parameter of the around function.  The documentation states that it is in kilometers, but I am seeing strange results.  After creating my set of nearby points using around, I made the change above to find the calculated distance using candidate.dist.  I compared these values to the distance calculated by geokdbush.distance for the same points, and the are off by over a factor of 5 when I expected them to match.  I checked the geokdbush.distance result and it is the correct distance - I have no idea what the candidate.dist value represents.

Perhaps I am making a simple mistake, but I am not seeing it.

Here is a snippet of my code, in case it helps - coordinate is an array of points.
```
     coordinates.forEach( function(point) {

        var nearest70 = geokdbush.around(index,point.lng,point.lat); 

        console.log(point);

        nearest70.forEach( function(nearby) {  
           console.log('Nearby Point:');
           console.log(nearby.item.lat+'  '+nearby.item.lng);         
           console.log('Dist:');
           console.log(nearby.dist);
           console.log('goekdbush.distance');
           console.log(geokdbush.distance(point.lng,point.lat,nearby.item.lng,nearby.item.lat));
        });
       
    });   
```
Here is some of the curious output:
![image](https://user-images.githubusercontent.com/2495345/39081360-ea834272-44f4-11e8-9a65-18e1f4143820.png)

I am sorry to trouble you - I am sure it is something simple I am missing, but I as I mentioned, I am just a beginner.  Any advice would be welcome.

Thanks!

Scott
